"""Explicit workflow state machine. Centralized constants — no ad hoc status strings."""

# Job/run states (per spec's Execution Monitor)
DRAFT = "DRAFT"
QUEUED = "QUEUED"
RUNNING = "RUNNING"
WAITING_FOR_REVIEW = "WAITING_FOR_REVIEW"
EXECUTING = "EXECUTING"
VALIDATING = "VALIDATING"
GENERATING_EVIDENCE = "GENERATING_EVIDENCE"
WAITING_FOR_APPROVAL = "WAITING_FOR_APPROVAL"
APPROVED = "APPROVED"
COMPLETED = "COMPLETED"
BLOCKED = "BLOCKED"
FAILED = "FAILED"
CANCELLED = "CANCELLED"

# Pipeline stages
CREATED = "CREATED"
REQUIREMENT_ANALYSIS = "REQUIREMENT_ANALYSIS"
SERVICE_PLANNING = "SERVICE_PLANNING"
TEST_PLANNING = "TEST_PLANNING"
TEST_GENERATION = "TEST_GENERATION"
TEST_REVIEW = "TEST_REVIEW"                 # human checkpoint
CODE_GENERATION = "CODE_GENERATION"
API_EXECUTION = "API_EXECUTION"
CODE_VALIDATION = "CODE_VALIDATION"
TRACEABILITY = "TRACEABILITY"
EVIDENCE_GENERATION = "EVIDENCE_GENERATION"
EVIDENCE_REVIEW = "EVIDENCE_REVIEW"          # human checkpoint
ALM_APPROVAL = "ALM_APPROVAL"                # human checkpoint
ALM_ATTACHMENT = "ALM_ATTACHMENT"
DONE = "DONE"

PIPELINE = [
    CREATED, REQUIREMENT_ANALYSIS, SERVICE_PLANNING, TEST_PLANNING, TEST_GENERATION,
    TEST_REVIEW, CODE_GENERATION, API_EXECUTION, CODE_VALIDATION, TRACEABILITY,
    EVIDENCE_GENERATION, EVIDENCE_REVIEW, ALM_APPROVAL, ALM_ATTACHMENT, DONE,
]

HUMAN_CHECKPOINTS = {TEST_REVIEW, EVIDENCE_REVIEW, ALM_APPROVAL}
EXCEPTION = {BLOCKED, FAILED, CANCELLED}


def next_stage(stage: str) -> str:
    if stage not in PIPELINE:
        raise ValueError(f"Unknown stage {stage}")
    i = PIPELINE.index(stage)
    return PIPELINE[i + 1] if i + 1 < len(PIPELINE) else DONE
